# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10E9UPgjA00Ajt7pvWREvuVjgvUd9i2vR
"""

import pandas as pd
df = pd.DataFrame({    'Ism':[ 'Xursandbek','Aziza','Robiya','Hojiakbar','Muxammadjon','Ilxom','Zikirillo'         ],
                       'Familya':['Abduxakimov','Sharifova','Xusanova','Azizbloyev','Doltaboyev','Eshboyev','Mamadaliyev'       ],
                       'Yoshi': ['20','20','20','20','20','19','19',      ],
                       'Kursi':['2','2','2','2','2','2','2'     ]


  })
print(df)

df.to_excel('malumot.xlsx', index=False, sheet_name='Sheet')